"""Core Planning and Retrieval Data Models for NewsLens-AI."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

from pydantic import BaseModel, Field

ToolName = Literal[
    "sql_analytics",
    "hybrid_search",
    "timeline_builder",
    "entity_search",
    "coverage_analysis",
    "web_search",
    "inspect_visual_asset",
    "dynamic_analysis",
]

QueryArchetype = Literal[
    "factual_lookup",
    "thematic_timeline",
    "quantitative_trend",
    "cross_newspaper_comparison",
    "entity_deep_dive",
    "article_catalog",
    "macro_summary",
    "negative_coverage_audit",
    "analytical_computation",
]

SectionFormat = Literal[
    "narrative",
    "bullet_list",
    "markdown_table",
    "metric_card",
    "timeline",
]


class SectionSpec(BaseModel):
    """Specification of an individual section designed for the answer."""

    title: str = Field(..., description="Markdown H3 header (e.g. '### ⚡ Executive Summary')")
    format_type: SectionFormat = Field(default="narrative", description="Visual format type for this section")
    content_focus: str = Field(default="", description="Core subject matter, angle, or data to emphasize in this section")
    target_length: str = Field(default="", description="Target length guidance (e.g. '1-2 concise paragraphs', '3-5 bullets')")


class AnswerBlueprint(BaseModel):
    """Planner-designed blueprint specifying the tailored structure and constraints of the answer."""

    user_intent: str = Field(default="", description="High-level interpretation of the user query intent")
    overall_tone: str = Field(default="authoritative_journalistic", description="Editorial tone for the brief")
    target_word_count: int | None = Field(default=None, description="Explicit target or max word count if requested by the user")
    sections: list[SectionSpec] = Field(default_factory=list, description="Ordered list of section specifications")
    table_columns: list[str] | None = Field(default=None, description="Explicit column headers if a markdown table is specified")
    prohibited_elements: list[str] = Field(default_factory=list, description="Explicitly prohibited content or formats")


@dataclass
class PlannedToolCall:
    """A tool execution step generated by the planner."""

    tool_name: str
    arguments: dict[str, Any] = field(default_factory=dict)
    purpose: str = ""


@dataclass
class PlanResult:
    """The structured planning outcome."""

    archetype: str
    reasoning: str
    tool_calls: list[PlannedToolCall]
    answer_blueprint: AnswerBlueprint | None = None


class ToolCallSpec(BaseModel):
    """Specification for a single tool invocation generated by the LLM."""

    tool_name: ToolName = Field(..., description="The name of the retrieval tool to execute")
    arguments: dict[str, Any] = Field(default_factory=dict, description="Arguments dictionary for this tool")
    purpose: str = Field(default="", description="1-sentence reason explaining what this tool call gathers")


class AgentPlan(BaseModel):
    """Structured plan returned by the LLM containing direct tool calls and dynamic answer blueprint."""

    thought_process: str = Field(default="", description="Chain-of-thought analysis of user intent")
    archetype: QueryArchetype = Field(default="factual_lookup", description="Archetype of the query")
    tool_calls: list[ToolCallSpec] = Field(default_factory=list, description="Ordered list of 1-3 tool calls to execute")
    answer_blueprint: AnswerBlueprint | None = Field(default=None, description="Dynamic specification for the answer format and structure")

    # Legacy fields for backward compatibility with existing test fixtures and mocks
    primary_tool: str | None = None
    arguments: Any = None
    include_secondary_hybrid_search: bool = False
    secondary_search_query: str | None = None


# Backward compatibility alias
QueryPlan = AgentPlan


class ExtractedToolArguments(BaseModel):
    """Legacy container for backwards-compatible test imports."""

    newspaper_name: str | None = None
    issue_date: str | None = None
    date_from: str | None = None
    date_to: str | None = None
    target_dates: list[str] = Field(default_factory=list)
    comparison_newspaper: str | None = None
    target_newspapers: list[str] = Field(default_factory=list)
    issue_id: int | None = None
    page_filter: str | None = None
    exclude_page_filter: str | None = None
    category_filter: str | None = None
    analysis_type: str | None = None
    query: str | None = None
    top_k: int = 6


__all__ = [
    "AgentPlan",
    "AnswerBlueprint",
    "ExtractedToolArguments",
    "PlanResult",
    "PlannedToolCall",
    "QueryArchetype",
    "QueryPlan",
    "SectionFormat",
    "SectionSpec",
    "ToolCallSpec",
    "ToolName",
]
