"""Core Planning and Retrieval Data Models for NewsLens-AI."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

from pydantic import BaseModel, Field

ToolName = Literal[
    "sql_analytics",
    "hybrid_search",
    "timeline_builder",
    "entity_search",
    "coverage_analysis",
    "web_search",
    "inspect_visual_asset",
]

QueryArchetype = Literal[
    "factual_lookup",
    "thematic_timeline",
    "quantitative_trend",
    "cross_newspaper_comparison",
    "entity_deep_dive",
    "article_catalog",
    "macro_summary",
    "negative_coverage_audit",
]


@dataclass
class PlannedToolCall:
    """A tool execution step generated by the planner."""

    tool_name: str
    arguments: dict[str, Any] = field(default_factory=dict)
    purpose: str = ""


@dataclass
class PlanResult:
    """The structured planning outcome."""

    archetype: str
    reasoning: str
    tool_calls: list[PlannedToolCall]


class ToolCallSpec(BaseModel):
    """Specification for a single tool invocation generated by the LLM."""

    tool_name: ToolName = Field(..., description="The name of the retrieval tool to execute")
    arguments: dict[str, Any] = Field(default_factory=dict, description="Arguments dictionary for this tool")
    purpose: str = Field(default="", description="1-sentence reason explaining what this tool call gathers")


class AgentPlan(BaseModel):
    """Structured plan returned by the LLM containing direct tool calls."""

    thought_process: str = Field(default="", description="Chain-of-thought analysis of user intent")
    archetype: QueryArchetype = Field(default="factual_lookup", description="Archetype of the query")
    tool_calls: list[ToolCallSpec] = Field(default_factory=list, description="Ordered list of 1-3 tool calls to execute")

    # Legacy fields for backward compatibility with existing test fixtures and mocks
    primary_tool: str | None = None
    arguments: Any = None
    include_secondary_hybrid_search: bool = False
    secondary_search_query: str | None = None


# Backward compatibility alias
QueryPlan = AgentPlan


class ExtractedToolArguments(BaseModel):
    """Legacy container for backwards-compatible test imports."""

    newspaper_name: str | None = None
    issue_date: str | None = None
    date_from: str | None = None
    date_to: str | None = None
    target_dates: list[str] = Field(default_factory=list)
    comparison_newspaper: str | None = None
    target_newspapers: list[str] = Field(default_factory=list)
    issue_id: int | None = None
    page_filter: str | None = None
    exclude_page_filter: str | None = None
    category_filter: str | None = None
    analysis_type: str | None = None
    query: str | None = None
    top_k: int = 6


__all__ = [
    "AgentPlan",
    "ExtractedToolArguments",
    "PlanResult",
    "PlannedToolCall",
    "QueryArchetype",
    "QueryPlan",
    "ToolCallSpec",
    "ToolName",
]
