"""Query Planner: True Agentic Direct Tool Planning and deterministic fallback."""

from __future__ import annotations

import contextlib
import json
import re
from dataclasses import dataclass, field
from typing import Any, Literal

from pydantic import BaseModel, Field

from app.core.logging import get_logger
from app.providers.base import ChatModelProvider, Message
from app.providers.registry import get_registry

logger = get_logger(__name__)

ToolName = Literal[
    "sql_analytics",
    "hybrid_search",
    "timeline_builder",
    "entity_search",
    "coverage_analysis",
    "web_search",
]

QueryArchetype = Literal[
    "factual_lookup",
    "thematic_timeline",
    "quantitative_trend",
    "cross_newspaper_comparison",
    "entity_deep_dive",
    "article_catalog",
    "macro_summary",
    "negative_coverage_audit",
]


# ---------------------------------------------------------------------------
# Core Planning Data Models
# ---------------------------------------------------------------------------

@dataclass
class PlannedToolCall:
    """A tool execution step generated by the planner."""

    tool_name: str
    arguments: dict[str, Any] = field(default_factory=dict)
    purpose: str = ""


@dataclass
class PlanResult:
    """The structured planning outcome."""

    archetype: str
    reasoning: str
    tool_calls: list[PlannedToolCall]


class ToolCallSpec(BaseModel):
    """Specification for a single tool invocation generated by the LLM."""

    tool_name: ToolName = Field(..., description="The name of the retrieval tool to execute")
    arguments: dict[str, Any] = Field(default_factory=dict, description="Arguments dictionary for this tool")
    purpose: str = Field(default="", description="1-sentence reason explaining what this tool call gathers")


class AgentPlan(BaseModel):
    """Structured plan returned by the LLM containing direct tool calls."""

    thought_process: str = Field(default="", description="Chain-of-thought analysis of user intent")
    archetype: QueryArchetype = Field(default="factual_lookup", description="Archetype of the query")
    tool_calls: list[ToolCallSpec] = Field(default_factory=list, description="Ordered list of 1-3 tool calls to execute")

    # Legacy fields for backward compatibility with existing test fixtures and mocks
    primary_tool: str | None = None
    arguments: Any = None
    include_secondary_hybrid_search: bool = False
    secondary_search_query: str | None = None


# Backward compatibility aliases
QueryPlan = AgentPlan


class ExtractedToolArguments(BaseModel):
    """Legacy container for backwards-compatible test imports."""

    newspaper_name: str | None = None
    issue_date: str | None = None
    date_from: str | None = None
    date_to: str | None = None
    target_dates: list[str] = Field(default_factory=list)
    comparison_newspaper: str | None = None
    target_newspapers: list[str] = Field(default_factory=list)
    issue_id: int | None = None
    page_filter: str | None = None
    exclude_page_filter: str | None = None
    category_filter: str | None = None
    analysis_type: str | None = None
    query: str | None = None
    top_k: int = 6


# ---------------------------------------------------------------------------
# Planner System Prompt for Direct Agentic Tool Planning
# ---------------------------------------------------------------------------

PLANNER_SYSTEM_PROMPT = """You are the expert Query Planner for NewsLens-AI, an agentic intelligence system over broadsheet newspapers.
Analyze the user's query, understand their underlying intent, produce step-by-step reasoning, and directly schedule the optimal ordered sequence of 1 to 3 tool calls.

### 🛠️ AVAILABLE RETRIEVAL TOOLS
1. `sql_analytics`: Relational system of record.
   - Arguments: {"analysis_type": "issue_summary" | "count_articles" | "coverage_difference", "newspaper_name": str, "issue_date": "YYYY-MM-DD", "category_filter": str, "page_filter": str, "query": str}
   - Use for: Catalogs, section manifests, whole issue overviews, article counts, or cross-newspaper article differences.
2. `hybrid_search`: Dense vector + BM25 keyword search for factual answers, quotes, and specific events.
   - Arguments: {"query": str, "newspaper_name": str, "date_from": str, "date_to": str, "page_filter": str, "category_filter": str, "top_k": int}
   - Use for: Point-in-time facts, quotes, event details, or targeted content.
3. `timeline_builder`: Chronological evolution and milestone articles.
   - Arguments: {"query": str, "limit": int}
   - Use for: Evolution over time, trajectories, and multi-date developments.
4. `entity_search`: Multi-hop entity network search and profiles.
   - Arguments: {"entity_name": str, "top_k": int}
   - Use for: Deep profiles of specific people or corporations.
5. `coverage_analysis`: Unreported news and negative coverage audit.
   - Arguments: {"query": str, "target_date": str}
   - Use for: Identifying what a newspaper omitted or missed across the archive.
6. `web_search`: Live internet search.
   - Arguments: {"query": str, "num_results": int}
   - Use for: Real-time current events outside the archive.

### 📚 FEW-SHOT EXAMPLES
Query: "What happened to Tata Power on page 3?"
Output: {"thought_process": "Factual question about Tata Power on page 3. Direct hybrid search bounded to page 3.", "archetype": "factual_lookup", "tool_calls": [{"tool_name": "hybrid_search", "arguments": {"query": "Tata Power", "page_filter": "3", "top_k": 6}, "purpose": "Search page 3 for Tata Power reporting"}]}

Query: "List all health news in The Goan on 2026-08-01"
Output: {"thought_process": "Relational catalog query for health articles in The Goan.", "archetype": "article_catalog", "tool_calls": [{"tool_name": "sql_analytics", "arguments": {"newspaper_name": "The Goan", "issue_date": "2026-08-01", "category_filter": "Health", "analysis_type": "issue_summary"}, "purpose": "Retrieve complete manifest of Health articles"}]}

Query: "Compare all available newspapers dated 1/8/2026 on health related news"
Output: {"thought_process": "Cross-newspaper domain comparison on health. First fetch SQL manifest for all newspapers on that date, then retrieve comparative excerpts.", "archetype": "cross_newspaper_comparison", "tool_calls": [{"tool_name": "sql_analytics", "arguments": {"issue_date": "2026-08-01", "category_filter": "Health", "analysis_type": "issue_summary", "query": "health related news"}, "purpose": "Fetch complete manifest of health articles across all newspapers"}, {"tool_name": "hybrid_search", "arguments": {"query": "health related news", "category_filter": "Health", "date_from": "2026-08-01", "date_to": "2026-08-01", "top_k": 12}, "purpose": "Retrieve comparative excerpts across broadsheet editions"}]}
"""


# ---------------------------------------------------------------------------
# Deterministic Brand & Section Patterns
# ---------------------------------------------------------------------------

_KNOWN_BRANDS_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"\b(?:the\s+)?goan(?:\s+everyday)?\b", re.I), "The Goan"),
    (re.compile(r"\b(?:the\s+)?economic\s+times\b|\bthe\s+economics\s+times\b|\beconomics\s+times\b", re.I), "The Economic Times"),
    (re.compile(r"\b(?:the\s+)?new\s+york\s+times\b|\bNYT\b", re.I), "The New York Times"),
    (re.compile(r"\b(?:the\s+)?times\s+of\s+india\b|\bTOI\b", re.I), "The Times of India"),
    (re.compile(r"\b(?:the\s+)?wall\s+street\s+journal\b|\bWSJ\b", re.I), "The Wall Street Journal"),
    (re.compile(r"\b(?:the\s+)?washington\s+post\b|\bWAPO\b", re.I), "The Washington Post"),
    (re.compile(r"\b(?:the\s+)?financial\s+times\b|\bFT\b", re.I), "Financial Times"),
    (re.compile(r"\b(?:the\s+)?guardian\b", re.I), "The Guardian"),
    (re.compile(r"\bbusiness\s+standard\b|\bBS\b", re.I), "Business Standard"),
    (re.compile(r"\b(?:the\s+)?indian\s+express\b|\bIE\b", re.I), "The Indian Express"),
    (re.compile(r"\b(?:the\s+)?hindu\b", re.I), "The Hindu"),
    (re.compile(r"\bhindustan\s+times\b|\bHT\b", re.I), "Hindustan Times"),
    (re.compile(r"\bmint\b|\blivemint\b", re.I), "Mint"),
    (re.compile(r"\b(?:the\s+)?daily\s+tribune\b|\btribune\b", re.I), "The Daily Tribune"),
    (re.compile(r"\b(?:the\s+)?daily\s+chronicle\b|\bchronicle\b", re.I), "The Daily Chronicle"),
    (re.compile(r"\bdaily\s+broadsheet\b", re.I), "Daily Broadsheet"),
    (re.compile(r"\b(?:(?:the|he)\s+)?morning\s+standard\b|\bmorning\s+standard\b", re.I), "The Morning Standard"),
    (re.compile(r"\b(?:the\s+)?financial\s+chronicle\b", re.I), "Financial Chronicle"),
    (re.compile(r"\b(?:the\s+)?daily\s+record\b", re.I), "The Daily Record"),
]

_SECTION_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"\b(sports?|athletics?|cricket|tennis|football|soccer|olympics?|tournaments?|ipl|bcci|icc|grand\s+slam|badminton|golf)\b", re.I), "Sports"),
    (re.compile(r"\b(entertainment|cinema|movies?|films?|bollywood|hollywood|arts?|music|concerts?|theatre|ott|actors?|actress(?:es)?)\b", re.I), "Entertainment"),
    (re.compile(r"\b(science|space|isro|nasa|satellites?|rockets?|astronomy|climate|environment|wildlife|forest|ocean|ecology)\b", re.I), "Science & Environment"),
    (re.compile(r"\b(tech|technology|ai|startups?|semiconductors?|chips?|software|fintech|gadgets?|cybersecurity|cloud|algorithms?)\b", re.I), "Technology"),
    (re.compile(r"\b(business|markets?|stocks?|shares|sensex|nifty|equities|ipo|corporate|companies|banking|finance|financial)\b", re.I), "Business & Markets"),
    (re.compile(r"\b(economy|economic|macroeconomics?|inflation|gdp|cpi|wpi|taxation|gst|tariffs?|budget|fiscal)\b", re.I), "Economy & Policy"),
    (re.compile(r"\b(politics|political|elections?|voters?|parliament|lok\s+sabha|rajya\s+sabha|ministers?|cabinet|bjp|congress)\b", re.I), "Politics"),
    (re.compile(r"\b(health|healthcare|hospitals?|doctors?|pharma|pharmaceuticals?|medicine|medicines?|vaccines?|diseases?)\b", re.I), "Health"),
    (re.compile(r"\b(crime|courts?|legal|law|supreme\s+court|high\s+court|judges?|verdicts?|bail|cbi|ed|police|arrests?|scams?|fraud)\b", re.I), "Crime & Law"),
    (re.compile(r"\b(opinion|editorials?|columns?|op-ed|commentary|viewpoints?|perspectives?)\b", re.I), "Opinion/Editorial"),
    (re.compile(r"\b(world|international|global|diplomacy|foreign\s+affairs|treaty|summit|united\s+nations|g20|brics)\b", re.I), "World/International"),
    (re.compile(r"\b(lifestyle|travel|tourism|food|dining|wellness|fitness|luxury|automotive)\b", re.I), "Lifestyle"),
]


def extract_parameters_from_query(query: str) -> dict[str, Any]:
    """Extract explicit entity parameters (newspaper, issue ID, date, section/category, page) from query."""
    params: dict[str, Any] = {}
    if not query:
        return params

    # 1. Multi-Newspaper Brand Extraction
    matched_brands: list[tuple[int, str]] = []
    for pat, brand in _KNOWN_BRANDS_PATTERNS:
        for brand_m in pat.finditer(query):
            matched_brands.append((brand_m.start(), brand))

    if matched_brands:
        matched_brands.sort(key=lambda x: x[0])
        ordered_brands: list[str] = []
        for _, b in matched_brands:
            if b not in ordered_brands:
                ordered_brands.append(b)

        params["target_newspapers"] = ordered_brands
        params["newspaper_name"] = ordered_brands[0]
        if len(ordered_brands) >= 2:
            params["comparison_newspaper"] = ordered_brands[1]

        q_lower = query.lower()
        if any(w in q_lower for w in ["but not in", "not in", "absent", "exclusive", "omitted", "missing from"]):
            params["is_differential"] = True
            params["source_newspaper"] = ordered_brands[0]
            if len(ordered_brands) >= 2:
                params["comparison_newspaper"] = ordered_brands[1]

    # 2. Issue ID Extraction
    iss_match = re.search(r"\bissue\s*(?:id\s*[:=]?\s*|\#\s*|no\.?\s*|number\s*)?(\d+)\b", query, re.I)
    if iss_match:
        with contextlib.suppress(ValueError):
            params["issue_id"] = int(iss_match.group(1))

    # 3. Date Extraction
    found_dates: list[str] = []
    # YYYY-MM-DD
    for iso_m in re.finditer(r"\b(\d{4})[/-](\d{1,2})[/-](\d{1,2})\b", query):
        year_val, month_val, day_val = int(iso_m.group(1)), int(iso_m.group(2)), int(iso_m.group(3))
        iso_str = f"{year_val:04d}-{month_val:02d}-{day_val:02d}"
        if iso_str not in found_dates:
            found_dates.append(iso_str)

    # DD/MM/YYYY or DD-MM-YYYY
    for dmy_m in re.finditer(r"\b(\d{1,2})[/-](\d{1,2})[/-](\d{4})\b", query):
        day_val, month_val, year_val = int(dmy_m.group(1)), int(dmy_m.group(2)), int(dmy_m.group(3))
        iso_str = f"{year_val:04d}-{month_val:02d}-{day_val:02d}"
        if iso_str not in found_dates:
            found_dates.append(iso_str)

    # Named months
    month_map = {
        "jan": 1, "january": 1, "feb": 2, "february": 2, "mar": 3, "march": 3,
        "apr": 4, "april": 4, "may": 5, "june": 6, "jun": 6, "july": 7, "jul": 7,
        "aug": 8, "august": 8, "sep": 9, "sept": 9, "september": 9, "oct": 10,
        "october": 10, "nov": 11, "november": 11, "dec": 12, "december": 12,
    }
    for m1 in re.finditer(r"\b(\d{1,2})(?:st|nd|rd|th)?\s+([a-zA-Z]+)(?:,)?\s+(\d{4})\b", query):
        if m1.group(2).lower() in month_map:
            day_val, month_val, year_val = int(m1.group(1)), month_map[m1.group(2).lower()], int(m1.group(3))
            iso_str = f"{year_val:04d}-{month_val:02d}-{day_val:02d}"
            if iso_str not in found_dates:
                found_dates.append(iso_str)

    for m2 in re.finditer(r"\b([a-zA-Z]+)\s+(\d{1,2})(?:st|nd|rd|th)?(?:,)?\s+(\d{4})\b", query):
        if m2.group(1).lower() in month_map:
            month_val, day_val, year_val = month_map[m2.group(1).lower()], int(m2.group(2)), int(m2.group(3))
            iso_str = f"{year_val:04d}-{month_val:02d}-{day_val:02d}"
            if iso_str not in found_dates:
                found_dates.append(iso_str)

    if found_dates:
        params["target_dates"] = found_dates
        params["issue_date"] = found_dates[0]
        if len(found_dates) >= 2:
            sorted_dates = sorted(found_dates)
            params["date_from"] = sorted_dates[0]
            params["date_to"] = sorted_dates[-1]

    # 4. Section / Category Extraction (mask matched brands to avoid false bleed like 'The Economic Times' matching 'Economy')
    query_for_sections = query
    for pat, _ in _KNOWN_BRANDS_PATTERNS:
        query_for_sections = pat.sub(" ", query_for_sections)

    for pat, cat_name in _SECTION_PATTERNS:
        if pat.search(query_for_sections):
            params["category_filter"] = cat_name
            break

    return params


def _build_targeted_web_query(query: str) -> str:
    """Transform conversational prompts into high-precision search queries."""
    if not query:
        return ""
    cleaned = query.strip()
    prefix_patterns = [
        r"^(?:can\s+you\s+|could\s+you\s+|would\s+you\s+|please\s+)+",
        r"^(?:tell\s+me\s+(?:about|more\s+about)?|summarize|explain|what\s+is|what\s+are|what\s+happened\s+(?:to|with)?|who\s+is|who\s+was|search\s+for|find\s+(?:news\s+about|information\s+on)?|give\s+me\s+(?:a\s+summary\s+of|details\s+about)?|overview\s+of)\s+(?:the\s+|a\s+|an\s+)?",
    ]
    for _ in range(3):
        prev = cleaned
        for pattern in prefix_patterns:
            cleaned = re.sub(pattern, "", cleaned, flags=re.IGNORECASE).strip()
        if cleaned == prev:
            break
    cleaned = re.sub(r"[\?\.\!]+$", "", cleaned).strip()
    return cleaned if len(cleaned) >= 3 else query.strip()


def resolve_tool_sequence(archetype: str, query: str, **kwargs: Any) -> list[PlannedToolCall]:
    """Backward-compatible helper delegating to QueryPlanner deterministic heuristic planner."""
    planner = QueryPlanner()
    res = planner._plan_query_heuristic(query)
    return res.tool_calls


# ---------------------------------------------------------------------------
# QueryPlanner Class (True Agentic Direct Tool Calling + Heuristic Fallback)
# ---------------------------------------------------------------------------

class QueryPlanner:
    """Agentic Query Planner with True Direct Tool Calling and Lean Deterministic Fallback."""

    def __init__(self, provider: ChatModelProvider | None = None) -> None:
        self._provider = provider

    def _get_provider_candidates(self, model_override: str | None = None) -> list[ChatModelProvider]:
        """Resolve LLM provider candidates for planning failover."""
        if self._provider is not None and not model_override:
            return [self._provider]

        candidates: list[ChatModelProvider] = []
        seen_keys: set[str] = set()

        try:
            reg = get_registry()
            primary = reg.get_chat_provider(model_override) if model_override else reg.get_provider("query_planner")
            if isinstance(primary, ChatModelProvider):
                candidates.append(primary)
                seen_keys.add(f"{getattr(primary, 'provider_name', '')}:{getattr(primary, '_model', '')}")
        except Exception as e:
            logger.warning("Could not resolve primary provider for QueryPlanner", extra={"error": str(e)})

        failover_keys = [
            "nvidia_nemotron",
            "openrouter_nemotron",
            "openrouter_gemma4_26b",
            "gemini_flash",
            "groq_compound",
            "openai_gpt4o_mini",
            "ollama_llama3",
            "ollama_deepseek",
        ]
        try:
            reg = get_registry()
            for k in failover_keys:
                try:
                    p = reg.get_chat_provider(k)
                    if p:
                        ident = f"{getattr(p, 'provider_name', '')}:{getattr(p, '_model', '')}"
                        if ident not in seen_keys:
                            seen_keys.add(ident)
                            candidates.append(p)
                except Exception:
                    continue
        except Exception:
            pass

        return candidates

    async def plan_query_async(
        self,
        query: str,
        enable_web_search: bool = False,
        model_override: str | None = None,
        archive_context: str | None = None,
        active_issue_date: str | None = None,
        active_newspapers: list[str] | None = None,
    ) -> PlanResult:
        """Plan query using true direct agentic tool calling with graceful heuristic fallback."""
        providers = self._get_provider_candidates(model_override)
        for provider in providers:
            try:
                user_content = f"Analyze and plan the following broadsheet research query:\nQuery: \"{query}\"\n"
                if archive_context:
                    user_content += f"\nACTIVE ARCHIVE STATE:\n{archive_context}\n"
                if active_issue_date or active_newspapers:
                    user_content += f"\nCONVERSATION WORKING CONTEXT:\nActive Date: {active_issue_date or 'None'}\nActive Newspapers: {', '.join(active_newspapers or []) or 'None'}\n"
                user_content += "\nSchedule the exact tool calls needed to gather evidence for this query."

                messages = [
                    Message(role="system", content=PLANNER_SYSTEM_PROMPT),
                    Message(role="user", content=user_content),
                ]
                resp = await provider.complete(
                    messages=messages,
                    response_schema=AgentPlan.model_json_schema(),
                    temperature=0.0,
                    max_tokens=1024,
                )

                parsed_dict = resp.parsed if isinstance(resp.parsed, dict) else self._parse_json_plan(resp.text)
                if parsed_dict:
                    plan_obj = AgentPlan.model_validate(parsed_dict)
                    return self._build_plan_from_structured_model(
                        query=query,
                        plan_obj=plan_obj,
                        enable_web_search=enable_web_search,
                    )
            except Exception as ex:
                logger.warning(
                    "LLM Agentic Planning attempt failed on provider, trying failover candidate",
                    extra={"query": query[:50], "provider": getattr(provider, "provider_name", ""), "error": str(ex)},
                )

        # Fallback to lean deterministic router
        return self._plan_query_heuristic(
            query,
            enable_web_search=enable_web_search,
            active_issue_date=active_issue_date,
            active_newspapers=active_newspapers,
        )

    def plan_query(
        self,
        query: str,
        enable_web_search: bool = False,
        archive_context: str | None = None,
        active_issue_date: str | None = None,
        active_newspapers: list[str] | None = None,
    ) -> PlanResult:
        """Synchronous planning interface."""
        return self._plan_query_heuristic(
            query,
            enable_web_search=enable_web_search,
            active_issue_date=active_issue_date,
            active_newspapers=active_newspapers,
        )

    def classify_archetype(self, query: str) -> tuple[str, str]:
        """Classify query archetype synchronously."""
        res = self._plan_query_heuristic(query)
        return res.archetype, res.reasoning

    @staticmethod
    def _parse_json_plan(text: str) -> dict[str, Any] | None:
        """Extract and parse JSON from text, stripping reasoning tags and markdown fences."""
        if not text:
            return None
        cleaned = re.sub(r"<(thought|think)>.*?</\1>", "", text, flags=re.DOTALL).strip()
        cleaned = re.sub(r"^<(thought|think)>.*?</\1>", "", cleaned, flags=re.DOTALL).strip()
        if not cleaned:
            cleaned = text.strip()

        if "```json" in cleaned:
            cleaned = cleaned.split("```json")[1].split("```")[0].strip()
        elif "```" in cleaned:
            cleaned = cleaned.split("```")[1].split("```")[0].strip()

        try:
            res = json.loads(cleaned)
            if isinstance(res, dict):
                return res
        except Exception:
            pass

        match = re.search(r"(\{.*\})", cleaned, re.DOTALL)
        if match:
            with contextlib.suppress(Exception):
                res = json.loads(match.group(1))
                if isinstance(res, dict):
                    return res
        return None

    def _build_plan_from_structured_model(
        self,
        query: str,
        plan_obj: AgentPlan,
        enable_web_search: bool = False,
    ) -> PlanResult:
        """Translate AgentPlan into PlanResult, executing direct tool calls or legacy adapter."""
        extracted = extract_parameters_from_query(query)
        tool_calls: list[PlannedToolCall] = []

        archetype = plan_obj.archetype
        if archetype == "macro_summary":
            archetype = "quantitative_trend"
        elif archetype == "negative_coverage_audit":
            archetype = "cross_newspaper_comparison"

        # 1. Direct tool calling (Option 2)
        if plan_obj.tool_calls:
            for spec in plan_obj.tool_calls:
                args = dict(spec.arguments)

                # Ground truth parameter reconciliation and hallucination pruning
                if extracted.get("newspaper_name"):
                    if args.get("newspaper_name") and args["newspaper_name"] != extracted["newspaper_name"]:
                        args["newspaper_name"] = extracted["newspaper_name"]
                elif args.get("newspaper_name"):
                    brand_tokens = [w.lower() for w in str(args["newspaper_name"]).split() if w.lower() not in {"the", "of", "and"}]
                    if not any(tok in query.lower() for tok in brand_tokens):
                        args.pop("newspaper_name", None)

                if extracted.get("issue_date"):
                    if args.get("issue_date") and args["issue_date"] != extracted["issue_date"]:
                        args["issue_date"] = extracted["issue_date"]
                elif args.get("issue_date"):
                    d_parts = str(args["issue_date"]).split("-")
                    if not any(part in query for part in d_parts):
                        args.pop("issue_date", None)

                if args.get("page_filter") is not None:
                    p_val = str(args["page_filter"]).strip()
                    if not re.search(rf"\bpage\s*{re.escape(p_val)}\b|\bp\.?\s*{re.escape(p_val)}\b", query, re.I):
                        args.pop("page_filter", None)

                tool_calls.append(PlannedToolCall(tool_name=spec.tool_name, arguments=args, purpose=spec.purpose))

        # 2. Legacy adapter: if mock/LLM provided primary_tool or arguments without tool_calls
        elif plan_obj.primary_tool or plan_obj.arguments:
            args = {}
            if isinstance(plan_obj.arguments, dict):
                args = dict(plan_obj.arguments)
            elif hasattr(plan_obj.arguments, "model_dump"):
                args = plan_obj.arguments.model_dump(exclude_none=True)

            # Ground truth reconciliation
            if extracted.get("issue_id") is not None and "issue_id" not in args:
                args["issue_id"] = extracted["issue_id"]

            if extracted.get("newspaper_name"):
                args["newspaper_name"] = extracted["newspaper_name"]
            elif args.get("newspaper_name"):
                brand_tokens = [w.lower() for w in str(args["newspaper_name"]).split() if w.lower() not in {"the", "of", "and"}]
                if not any(tok in query.lower() for tok in brand_tokens):
                    args.pop("newspaper_name", None)

            if extracted.get("issue_date"):
                args["issue_date"] = extracted["issue_date"]
            elif args.get("issue_date"):
                d_parts = str(args["issue_date"]).split("-")
                if not any(part in query for part in d_parts):
                    args.pop("issue_date", None)

            if args.get("page_filter") is not None:
                p_val = str(args["page_filter"]).strip()
                if not re.search(rf"\bpage\s*{re.escape(p_val)}\b|\bp\.?\s*{re.escape(p_val)}\b", query, re.I):
                    args.pop("page_filter", None)

            # Generic filler sanitization
            if args.get("query") and str(args["query"]).strip().lower() in {
                "newspaper coverage comparison", "coverage comparison", "coverage analysis",
                "newspaper comparison", "compare newspapers", "all available newspapers",
                "all newspaper", "cross newspaper comparison", "cross-edition frontpage and lead story comparison",
            }:
                if args.get("category_filter"):
                    args["query"] = f"{args['category_filter'].lower()} related news"
                else:
                    args["query"] = query

            # Dispatch based on archetype
            if archetype == "cross_newspaper_comparison":
                target_dt = args.get("issue_date") or extracted.get("issue_date")
                comp_np = args.get("comparison_newspaper") or extracted.get("comparison_newspaper")
                src_np = args.get("newspaper_name") or extracted.get("newspaper_name")
                is_differential = (
                    extracted.get("is_differential", False)
                    or plan_obj.archetype == "negative_coverage_audit"
                    or args.get("analysis_type") == "coverage_difference"
                )

                if src_np and comp_np and is_differential:
                    diff_args: dict[str, Any] = {
                        "analysis_type": "coverage_difference",
                        "newspaper_name": src_np,
                        "comparison_newspaper": comp_np,
                        "query": args.get("query", query),
                    }
                    if target_dt:
                        diff_args["issue_date"] = target_dt
                    tool_calls.append(PlannedToolCall("sql_analytics", diff_args, f"Coverage difference: {src_np} vs {comp_np}"))
                    tool_calls.append(PlannedToolCall("hybrid_search", {"query": args.get("query", query), "newspaper_name": src_np, "top_k": 10}, f"Articles from {src_np}"))
                elif plan_obj.primary_tool == "coverage_analysis" and not src_np and not args.get("category_filter") and not target_dt:
                    cov_args: dict[str, Any] = {"query": args.get("query", query)}
                    tool_calls.append(PlannedToolCall("coverage_analysis", cov_args, "Archive-wide negative coverage audit"))
                else:
                    # All newspapers or standard comparison
                    sql_args: dict[str, Any] = {
                        "analysis_type": "issue_summary",
                        "query": args.get("query", query),
                    }
                    if target_dt:
                        sql_args["issue_date"] = target_dt
                    if args.get("category_filter"):
                        sql_args["category_filter"] = args["category_filter"]
                    if src_np:
                        sql_args["newspaper_name"] = src_np
                    tool_calls.append(PlannedToolCall("sql_analytics", sql_args, "SQL article manifest"))

                    hs_args: dict[str, Any] = {
                        "query": args.get("query", query),
                        "top_k": 12,
                    }
                    if target_dt:
                        hs_args["date_from"] = target_dt
                        hs_args["date_to"] = target_dt
                    if args.get("category_filter"):
                        hs_args["category_filter"] = args["category_filter"]
                    if src_np:
                        hs_args["newspaper_name"] = src_np
                    tool_calls.append(PlannedToolCall("hybrid_search", hs_args, "Comparative article excerpts"))

                    if not src_np and target_dt and not args.get("category_filter"):
                        tool_calls.append(PlannedToolCall("coverage_analysis", {"query": args.get("query", query), "target_date": target_dt}, "Archive-wide negative coverage audit"))
            else:
                primary = plan_obj.primary_tool or ("sql_analytics" if archetype in ("quantitative_trend", "article_catalog") else "hybrid_search")
                tool_calls.append(PlannedToolCall(tool_name=primary, arguments=args, purpose=f"Execute {primary}"))
                if plan_obj.include_secondary_hybrid_search and primary != "hybrid_search":
                    tool_calls.append(PlannedToolCall("hybrid_search", {"query": plan_obj.secondary_search_query or query, "top_k": 6}, "Corroborating search"))

        # 3. Fallback if no tool calls produced
        if not tool_calls:
            heur = self._plan_query_heuristic(query, enable_web_search=enable_web_search)
            tool_calls = heur.tool_calls

        if enable_web_search and not any(t.tool_name == "web_search" for t in tool_calls):
            tool_calls.append(PlannedToolCall(tool_name="web_search", arguments={"query": _build_targeted_web_query(query), "num_results": 5}, purpose="Live internet news"))

        return PlanResult(archetype=archetype, reasoning=plan_obj.thought_process, tool_calls=tool_calls)

    def _plan_query_heuristic(
        self,
        query: str,
        enable_web_search: bool = False,
        active_issue_date: str | None = None,
        active_newspapers: list[str] | None = None,
    ) -> PlanResult:
        """Clean, deterministic single-pass intent routing for offline fallback."""
        q_lower = query.lower().strip()
        params = extract_parameters_from_query(query)

        newspaper = params.get("newspaper_name")
        issue_id = params.get("issue_id")
        issue_date = params.get("issue_date") or active_issue_date
        date_from = params.get("date_from") or issue_date
        date_to = params.get("date_to") or issue_date
        target_dates = params.get("target_dates") or ([issue_date] if issue_date else [])
        category = params.get("category_filter")
        is_diff = params.get("is_differential", False)
        comp_newspaper = params.get("comparison_newspaper")

        # Page extraction
        page_filter = None
        p_match = re.search(r"\b(?:page|pg|p\.?)\s*(\d{1,3})\b", q_lower)
        if p_match:
            page_filter = p_match.group(1)

        tool_calls: list[PlannedToolCall] = []

        # 1. Timeline / Chronological Trajectory
        if any(w in q_lower for w in ["timeline", "chronology", "chronological", "evolution", "over time", "history of", "progression"]):
            archetype = "thematic_timeline"
            tool_calls.append(PlannedToolCall("timeline_builder", {"query": query, "limit": 25}, "Aggregate chronological milestones"))
            tool_calls.append(PlannedToolCall("hybrid_search", {"query": query, "top_k": 8}, "Retrieve anchor articles"))

        # 2. Entity Deep Dive
        elif any(w in q_lower for w in ["everything about", "all mentions of", "profile the coverage", "profile of"]):
            archetype = "entity_deep_dive"
            clean_ent = re.sub(r"(?i)^(?:everything about|all mentions of|profile the coverage of|profile of)\s*", "", query).strip("?:!.,\"' ") or query
            tool_calls.append(PlannedToolCall("entity_search", {"entity_name": clean_ent, "top_k": 10}, f"Profile entity '{clean_ent}'"))
            tool_calls.append(PlannedToolCall("hybrid_search", {"query": query, "top_k": 8}, "Semantic context"))

        # 3. Single Newspaper Multi-Issue Comparison (same newspaper brand across multiple dates)
        elif newspaper and not comp_newspaper and len(target_dates) >= 2:
            archetype = "quantitative_trend"
            for dt_val in target_dates:
                tool_calls.append(PlannedToolCall("sql_analytics", {"analysis_type": "issue_summary", "newspaper_name": newspaper, "issue_date": dt_val, "query": query}, f"Manifest for {newspaper} on {dt_val}"))
            tool_calls.append(PlannedToolCall("hybrid_search", {"query": query, "newspaper_name": newspaper, "date_from": date_from, "date_to": date_to, "top_k": 10}, "Multi-issue articles"))

        # 4. Cross-Newspaper Comparison
        elif (
            comp_newspaper is not None
            or is_diff
            or any(w in q_lower for w in ["across newspapers", "across different papers", "all available", "all the available", "all newspapers", "both newspapers", "different papers", "different newspapers"])
            or bool(re.search(r"\b(?:compa[a-z]*|contrast[a-z]*|diff[a-z]*|versus|vs\.?)\b", q_lower))
        ):
            archetype = "cross_newspaper_comparison"
            target_dt = issue_date or date_from
            if newspaper and comp_newspaper and is_diff:
                tool_calls.append(PlannedToolCall("sql_analytics", {"analysis_type": "coverage_difference", "newspaper_name": newspaper, "comparison_newspaper": comp_newspaper, "issue_date": target_dt, "query": query}, f"Compute stories in {newspaper} absent from {comp_newspaper}"))
                tool_calls.append(PlannedToolCall("hybrid_search", {"query": query, "newspaper_name": newspaper, "date_from": target_dt, "date_to": target_dt, "top_k": 10}, f"Retrieve articles from {newspaper}"))
            elif newspaper and comp_newspaper:
                for np_name in [newspaper, comp_newspaper]:
                    args: dict[str, Any] = {"analysis_type": "issue_summary", "newspaper_name": np_name, "issue_date": target_dt, "query": query}
                    if category:
                        args["category_filter"] = category
                    tool_calls.append(PlannedToolCall("sql_analytics", args, f"Retrieve manifest for {np_name}"))
                hs_args: dict[str, Any] = {"query": query, "date_from": target_dt, "date_to": target_dt, "top_k": 12}
                if category:
                    hs_args["category_filter"] = category
                tool_calls.append(PlannedToolCall("hybrid_search", hs_args, f"Comparative articles across {newspaper} and {comp_newspaper}"))
            elif not target_dt:
                # General cross-newspaper topic comparison without a specific issue date (e.g. "Compare coverage of tax law across papers")
                hs_args = {"query": query, "top_k": 12}
                if category:
                    hs_args["category_filter"] = category
                tool_calls.append(PlannedToolCall("hybrid_search", hs_args, "Comparative articles across broadsheet editions"))
                tool_calls.append(PlannedToolCall("coverage_analysis", {"query": query}, "Archive-wide coverage comparison"))
            else:
                # All newspapers on a specific date (e.g. "comapare all the available newspaper dated 1/8/2026")
                sql_args = {"analysis_type": "issue_summary", "issue_date": target_dt, "query": query}
                if category:
                    sql_args["category_filter"] = category
                tool_calls.append(PlannedToolCall("sql_analytics", sql_args, f"Manifest across all newspapers on {target_dt}"))

                hs_args = {"query": query, "date_from": target_dt, "date_to": target_dt, "top_k": 12}
                if category:
                    hs_args["category_filter"] = category
                elif not newspaper and target_dt:
                    hs_args["page_filter"] = "1"
                tool_calls.append(PlannedToolCall("hybrid_search", hs_args, "Diverse articles across editions"))

                # Only schedule coverage audit if not scoped to a domain or if explicit audit keywords
                if not category or any(w in q_lower for w in ["omission", "miss", "omitted", "exclusive", "gap", "audit"]):
                    tool_calls.append(PlannedToolCall("coverage_analysis", {"query": query, "target_date": target_dt}, "Negative coverage audit"))

                # For full cross-newspaper comparisons dated, include coverage_comparison SQL analytics
                if not category and not newspaper:
                    tool_calls.append(PlannedToolCall("sql_analytics", {"analysis_type": "coverage_comparison", "target_date": target_dt, "query": query}, f"SQL coverage comparison on {target_dt}"))

        # 5. Quantitative Trend / Issue Manifest / Page Listings / Counts / Distribution
        elif (
            (page_filter and any(w in q_lower for w in ["article", "story", "stories", "no of", "how many", "list"]))
            or any(w in q_lower for w in [
                "how many", "count", "number of", "no of", "frequency", "trend", "distribution",
                "volume", "statistics", "summarize", "overview", "whole", "entire", "all articles",
                "list", "manifest", "today's paper", "edition", "what articles", "articles on",
            ])
            or (category and any(w in q_lower for w in ["news", "articles", "stories", "headlines"]))
        ):
            archetype = "quantitative_trend"
            is_count = any(w in q_lower for w in ["how many", "total articles", "number of articles", "count of articles"]) and not page_filter
            analysis_type = "count_articles" if is_count else "issue_summary"

            call_args: dict[str, Any] = {
                "analysis_type": analysis_type,
                "newspaper_name": newspaper,
                "issue_date": issue_date,
                "date_from": date_from,
                "date_to": date_to,
                "issue_id": issue_id,
                "page_filter": page_filter,
                "category_filter": category,
                "query": query,
            }
            tool_calls.append(PlannedToolCall("sql_analytics", {k: v for k, v in call_args.items() if v is not None}, f"SQL analytics ({analysis_type})"))
            if page_filter and any(w in q_lower for w in ["list", "articles on", "stories on", "all articles"]):
                p_hs = {"query": query, "page_filter": page_filter, "top_k": 6}
                if newspaper:
                    p_hs["newspaper_name"] = newspaper
                if date_from:
                    p_hs["date_from"] = date_from
                if date_to:
                    p_hs["date_to"] = date_to
                tool_calls.append(PlannedToolCall("hybrid_search", p_hs, f"Articles on Page {page_filter}"))

        # 6. Factual Lookup (Default)
        else:
            archetype = "factual_lookup"
            f_args: dict[str, Any] = {"query": query, "top_k": 6}
            if page_filter:
                f_args["page_filter"] = page_filter
            if newspaper:
                f_args["newspaper_name"] = newspaper
            if date_from:
                f_args["date_from"] = date_from
            if date_to:
                f_args["date_to"] = date_to
            tool_calls.append(PlannedToolCall("hybrid_search", f_args, "Search for factual evidence"))

        if enable_web_search:
            tool_calls.append(PlannedToolCall("web_search", {"query": _build_targeted_web_query(query), "num_results": 5}, "Live internet news"))

        return PlanResult(archetype=archetype, reasoning=f"Deterministic heuristic plan ({archetype})", tool_calls=tool_calls)
