"""Query Planner: Archetype classification and multi-step tool execution planning."""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any

from app.core.logging import get_logger

logger = get_logger(__name__)

TIMELINE_KEYWORDS = re.compile(
    r"\b(?:timeline|chronology|chronological|trace|evolution|over time|"
    r"history of|progression|sequence)\b",
    re.IGNORECASE,
)

TREND_KEYWORDS = re.compile(
    r"\b(?:how many|count|total articles|total pages|list all|all articles|"
    r"summarize issue|overview of|what articles|frequency|trend|trends|ratio|"
    r"percentage|distribution|statistics|volume|metric|no\.?\s*of\s*articles|number\s*of\s*articles)\b",
    re.IGNORECASE,
)

COMPARISON_KEYWORDS = re.compile(
    r"\b(?:compare|comparison|contrast|perspectives|different papers|"
    r"coverage across|differ|bias)\b",
    re.IGNORECASE,
)

ENTITY_KEYWORDS = re.compile(
    r"\b(?:everything about|all mentions of|profile|who is|what did .* say|coverage of)\b",
    re.IGNORECASE,
)

PAGE_PATTERN = re.compile(
    r"\b(?:page|pg|p\.)\s*([0-9]{1,3}|[A-Za-z]?[-–]?[0-9]{1,3})\b",
    re.IGNORECASE,
)

PAGE_ARTICLE_QUERY_PATTERN = re.compile(
    r"\b(?:list|how many|count|number of|no\.?\s*of|what|show|all)?\s*"
    r"(?:of\s*)?articles\b.*?\b(?:page|pg|p\.)\s*"
    r"([0-9]{1,3}|[A-Za-z]?[-–]?[0-9]{1,3})\b"
    r"|\b(?:page|pg|p\.)\s*([0-9]{1,3}|[A-Za-z]?[-–]?[0-9]{1,3})\b.*?"
    r"\b(?:articles|stories|news|manifest)\b",
    re.IGNORECASE,
)


@dataclass
class PlannedToolCall:
    """A tool execution step generated by the planner."""

    tool_name: str
    arguments: dict[str, Any]
    purpose: str


@dataclass
class PlanResult:
    """The structured planning outcome."""

    archetype: str
    reasoning: str
    tool_calls: list[PlannedToolCall]


class QueryPlanner:
    """Classifies user queries into 5 archetypes and creates targeted retrieval plans."""

    def classify_archetype(self, query: str) -> tuple[str, str]:
        """Determine archetype based on semantic cues and intent."""
        query_clean = query.strip()

        if PAGE_ARTICLE_QUERY_PATTERN.search(query_clean):
            return (
                "quantitative_trend",
                "User requested article listing or count for a specific newspaper page.",
            )
        elif TIMELINE_KEYWORDS.search(query_clean):
            return (
                "thematic_timeline",
                "User requested chronological event progression or evolution over time.",
            )
        elif TREND_KEYWORDS.search(query_clean):
            return (
                "quantitative_trend",
                "User requested statistical trends, frequencies, or volume distributions.",
            )
        elif COMPARISON_KEYWORDS.search(query_clean):
            return (
                "cross_newspaper_comparison",
                "User requested comparison of editorial perspectives across papers.",
            )
        elif ENTITY_KEYWORDS.search(query_clean):
            return (
                "entity_deep_dive",
                "User requested focused investigation of a specific entity or organization.",
            )
        else:
            return (
                "factual_lookup",
                "User requested factual point-in-time information or specific news event details.",
            )

    def plan_query(self, query: str) -> PlanResult:
        """Generate ordered tool invocations for the classified archetype."""
        archetype, reasoning = self.classify_archetype(query)
        tool_calls: list[PlannedToolCall] = []

        if archetype == "thematic_timeline":
            tool_calls.append(
                PlannedToolCall(
                    tool_name="timeline_builder",
                    arguments={"query": query, "limit": 30},
                    purpose="Aggregate chronological trajectory and milestone articles",
                )
            )
            tool_calls.append(
                PlannedToolCall(
                    tool_name="hybrid_search",
                    arguments={"query": query, "top_k": 8},
                    purpose="Retrieve key anchor articles for the timeline",
                )
            )

        elif archetype == "quantitative_trend":
            page_match = PAGE_ARTICLE_QUERY_PATTERN.search(query)
            is_issue_aggregate = bool(
                page_match
                or re.search(
                    r"\b(?:how many articles|how many pages|total articles|list all|"
                    r"all articles|summarize issue|overview of the issue|what articles|"
                    r"manifest|all headlines|no\.?\s*of\s*articles)\b",
                    query,
                    re.IGNORECASE,
                )
            )

            if page_match:
                page_token = [g for g in page_match.groups() if g is not None][0]
                tool_calls.append(
                    PlannedToolCall(
                        tool_name="sql_analytics",
                        arguments={
                            "analysis_type": "issue_summary",
                            "page_filter": page_token,
                            "query": query,
                        },
                        purpose=(
                            f"Query MySQL system of record for exact article count and "
                            f"manifest on Page {page_token}"
                        ),
                    )
                )
                tool_calls.append(
                    PlannedToolCall(
                        tool_name="hybrid_search",
                        arguments={"query": query, "page_filter": page_token, "top_k": 6},
                        purpose=f"Retrieve article content and snippets on Page {page_token}",
                    )
                )
            elif is_issue_aggregate:
                tool_calls.append(
                    PlannedToolCall(
                        tool_name="sql_analytics",
                        arguments={"analysis_type": "issue_summary", "query": query},
                        purpose=(
                            "Query MySQL system of record for exact article "
                            "counts, pages, and manifest"
                        ),
                    )
                )
            else:
                stop_words = {
                    "trend",
                    "frequency",
                    "ratio",
                    "show",
                    "what",
                    "many",
                    "count",
                }
                keywords = [
                    w for w in re.findall(r"\b[A-Za-z]{4,}\b", query) if w.lower() not in stop_words
                ]
                primary_term = keywords[0] if keywords else query

                tool_calls.append(
                    PlannedToolCall(
                        tool_name="sql_analytics",
                        arguments={"analysis_type": "entity_trends", "term": primary_term},
                        purpose="Calculate quantitative mention volume and frequency over time",
                    )
                )
                tool_calls.append(
                    PlannedToolCall(
                        tool_name="sql_analytics",
                        arguments={"analysis_type": "topic_distribution"},
                        purpose="Analyze topic volume and section prominence ratios",
                    )
                )
                tool_calls.append(
                    PlannedToolCall(
                        tool_name="hybrid_search",
                        arguments={"query": query, "top_k": 5},
                        purpose=(
                            "Retrieve representative qualitative examples for statistical findings"
                        ),
                    )
                )

        elif archetype == "cross_newspaper_comparison":
            tool_calls.append(
                PlannedToolCall(
                    tool_name="hybrid_search",
                    arguments={"query": query, "top_k": 12},
                    purpose="Retrieve multi-newspaper coverage across distinct publications",
                )
            )

        elif archetype == "entity_deep_dive":
            # Extract entity name
            cap_matches = re.findall(r"\b([A-Z][a-z]+(?:\s+[A-Z][a-z]+)*)\b", query)
            ent_name = cap_matches[0] if cap_matches else query

            tool_calls.append(
                PlannedToolCall(
                    tool_name="entity_search",
                    arguments={"entity_name": ent_name, "top_k": 10},
                    purpose=f"Retrieve high-salience articles mentioning entity '{ent_name}'",
                )
            )
            tool_calls.append(
                PlannedToolCall(
                    tool_name="hybrid_search",
                    arguments={"query": query, "top_k": 8},
                    purpose="Semantic search for broader context and editorial mentions",
                )
            )

        else:  # factual_lookup
            p_match = PAGE_PATTERN.search(query)
            if p_match:
                p_token = p_match.group(1)
                tool_calls.append(
                    PlannedToolCall(
                        tool_name="hybrid_search",
                        arguments={"query": query, "page_filter": p_token, "top_k": 6},
                        purpose=f"Execute hybrid search filtered to Page {p_token}",
                    )
                )
            else:
                tool_calls.append(
                    PlannedToolCall(
                        tool_name="hybrid_search",
                        arguments={"query": query, "top_k": 6},
                        purpose="Execute hybrid dense/sparse search for direct factual evidence",
                    )
                )

        logger.info(
            "Query planned",
            extra={
                "query": query[:40],
                "archetype": archetype,
                "tools_planned": len(tool_calls),
            },
        )

        return PlanResult(
            archetype=archetype,
            reasoning=reasoning,
            tool_calls=tool_calls,
        )
